### ISSUE TITLE
Meteor 1.2 does not update --> stylus@1.0.0 

### ISSUE THREAD

**Issue by stachrom** [rajit/meteor-accounts-ui-bootstrap-3#12]
Update to release METEOR@1.2-rc.17 is impossible:
While selecting package versions:             
error: Conflict: Constraint stylus@1.0.0 is not satisfied by stylus 2.511.0-rc.5.
Constraints on package "stylus":
* stylus@=2.511.0-rc.5 <- top level
* stylus@1.0.0 <- rajit:accounts-ui-bootstrap-3 1.2.3

This project is at the latest release which is compatible with your current package constraints.
stachrom@prometheus:/home/www/meteor/kursverwaltung$

**Comment by rajit** [comment]
I'm no longer maintaining this as ian:accounts-ui-bootstrap-3 is already there and kept up-to-date.

I've removed this from Atmosphere search and am going to remove this GitHub repository.
